feat(Badge): Added Background Color support to Badge
optimizely/oui pull request #1423
Opened 2020-09-28 21:34 UTC by zashraf1985

## Summary
Added Background Color support to `Badge`. I needed a darker version of grey for a project, added support for Background color which can take these additional colors as `backgroundColor`.
1. aqua
2. yellow
3. green
4. orange
5. pink
6. red
7. magenta
8. grey
9. purple
10. black

## Changelog Entry
[Feature] Updated **Badge** with new `backgroundColor` to support additional colors.

## Test Plan
1. Manually tested thoroughly.
2. All existing unit tests pass.

2020-09-28 22:08 UTC, spham1412 requested changes

2020-09-28 22:08 UTC, spham1412 commented on src/components/Badge/index.js
> +
Based on this logic, we're using both `color` and `backgroundColor` if both are provided through props. In this case, how are we handling it?

I prefer to use `color` first, if `color` is not provided, then use `backgroundColor`. If both are provided, what happens?

2020-09-30 16:57 UTC, zashraf1985 commented on src/components/Badge/index.js
> +
Added a check to only use `backgroundColor` when its available and `color` is `default`

2020-09-30 17:43 UTC, spham1412 approved these changes

2020-09-30 17:45 UTC, merged