feat(Sidebar): Make sidebar resizable on x-axis
optimizely/oui pull request #1432
Opened 2020-10-20 16:17 UTC by oakbani

## Summary

What did you change and why?

## Changelog Entry

## Test Plan

Please remember to add tests for all new functionality, and manually test for Accessibility (including keyboard navigation and screen reader usage)

## Jira

Please list and link the associated JIRA ticket

- [UXENG-XYZ](https://optimizely.atlassian.net/browse/UXENG-XYZ)

2020-10-21 17:49 UTC, spham1412 requested changes

2020-10-21 17:49 UTC, spham1412 commented on src/components/Sidebar/Sidebar.js
> +    <Resizable
Let's add a check for `isResizable`. If that's `false`, then we should return a simple `div` as before.

2020-10-22 09:37 UTC, oakbani commented
[Patch] Updated Sidebar with new props to make it resizable horizontally.

2020-10-22 18:13 UTC, spham1412 approved these changes

2020-10-22 18:14 UTC, spham1412 commented on src/components/Sidebar/Sidebar.js
> +
Remove this empty line please

2020-10-22 19:36 UTC, merged